### ISSUE TITLE
SfTextInputLayout is disproportionate

### ISSUE THREAD

**Issue by mikaelotowicz** [syncfusion/maui-toolkit#14]
SfTextInputLayout is disproportionate, I tried to set the height but the entry value appears cut off

![Captura de tela 2024-10-24 222449](https://github.com/user-attachments/assets/2aab961d-c66c-4ce3-835e-17545040ac7b)

**Comment by riccardominato** [comment]
I had the same issue, you can adjust it using `InputViewPadding` property.
