### ISSUE TITLE
In example replace .UseSyncfusionToolkit() with .ConfigureSyncfusionToolkit() in mauiprogram.cs

### ISSUE THREAD

**Issue by davefxy** [syncfusion/maui-toolkit#16]
In the example, use .ConfigureSyncfusionToolkit() in mauiprogram.cs instead of  .UseSyncfusionToolkit().
Update the MainPage.xaml with:
`        <chart:SfCartesianChart.Series>
            <chart:SplineSeries Label="High" EnableTooltip="True" EnableAnimation="True" ItemsSource="{Binding Data}" XBindingPath="Name" YBindingPath="Height" StrokeWidth="1" ShowMarkers="True" LegendIcon="SeriesType" >
                <chart:SplineSeries.MarkerSettings>
                    <chart:ChartMarkerSettings Width="8" Height="8" StrokeWidth="1"/>
                </chart:SplineSeries.MarkerSettings>
            </chart:SplineSeries>
        </chart:SfCartesianChart.Series>
`
In Xaml, the namespace that worked for me was:
xmlns:chart="clr-namespace:Syncfusion.Maui.Toolkit.Charts;assembly=Syncfusion.Maui.Toolkit"

Then the example will display the intended data. How do I get the code displayed above to appear properly as seperated lines?

**Comment by PaulAndersonS** [comment]
Hi @davefxy,
Thanks for the code suggestions. We have now updated the complete code example to the readme file

**Comment by davefxy** [comment]
Awesome library. Replaced MicroCharts.with yout library charts. Your library is just in time. MicroCharts was past end of life.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sat, Oct 26, 2024 at 12:00 AM, Paul ***@***.***> wrote:   


Hi @davefxy,
Thanks for the code suggestions. We have now updated the complete code example to the readme file
