### ISSUE TITLE
[Feature Request] Implement Numeric Entry control

### ISSUE THREAD

**Issue by PrithisIyyappan** [syncfusion/maui-toolkit#28]
## Description ##

A `NumericEntry` control that allows users to input only numeric values, supporting various formats such as integers, decimals, percentages, and currency. It offers customizable features like input validation, format masks, and display customization, ensuring that data entry is efficient, accurate, and tailored to specific application needs. This control is essential for maintaining numeric-only input with precise formatting and validation rules.

### Numeric Input Restriction ###
Ensures that only numeric values are entered, preventing invalid characters and reducing input errors.

### Customizable Input Masks ###
Supports different display formats such as currency symbols, percentage signs, and custom units for enhanced readability.

### Input Validation ###
Includes built-in validation rules such as min/max value enforcement, and configurable error messages to guide user input.

### Formatting Options ###
Supports localization and custom number formatting, adapting to various cultural settings for currency, decimal, and thousand separators.

### Placeholder and Prefix/Suffix ###
Offers placeholder text when the input is empty, as well as optional prefixes and suffixes (e.g., currency signs) for contextual display.

### Enhanced User Input Control ###
Reduces input errors by ensuring only valid numeric input is accepted, resulting in cleaner, validated data entry.

### Flexible Customization ###
Allows developers to tailor the control’s behavior to specific application requirements, enhancing user experience across various use cases.

### Efficient Data Entry ###
Increased speed and accuracy in numeric data entry by providing real-time validation.

### Financial Applications ###
Ideal for inputting amounts, prices, or financial data where only numeric input is allowed, and specific formats (currency) are required.

### E-commerce Platforms ###
Used for specifying quantities, prices, or discounts in shopping carts and checkout processes.

### Statistical and Data Collection Tools ###
Supports entry of numeric data in forms or surveys, where format consistency is essential.

### Inspiration from Other Platforms ###
A well-implemented NumericEntry control offers a familiar user experience, similar to numeric input fields seen in financial apps, POS systems, and form entry fields in web and mobile applications.

### Demos and Examples ###
Reference existing third-party examples or create interactive demos to showcase input restrictions, format options, and validation behavior.

## Acceptance Criteria ##

- [ ] The NumericEntry control restricts input to numeric values only.
- [ ] Supports customizable input masks for various numeric formats.
- [ ] Configurable min and max values with validation.
- [ ] Customizable formatting and localization support.
- [ ] Documentation and usage examples are provided.
- [ ] Unit and UI tests are added.

**Comment by PaulAndersonS** [comment]
Fixes #29
