### ISSUE TITLE
TabView's BindingContext is initialized for all tabs when the control is loaded in syncfusion tab For MAUI

### ISSUE THREAD

**Issue by Arviksain** [syncfusion/maui-toolkit#32]
TabView's BindingContext is initialized for all tabs when the control is loaded in syncfusion tab. This should not be the right case.
The case should be like 

eg:

tabview habing 3 tabs like tabitem1, tabitem2,tabitem3

so when tabview initialized then only initialize bindingcontext for tabitem1 not all the tabitems, like same way when tabitem2 clicked that time only initialize binding context for tabitem2 content.

that should be the architecture like devexpress tabview

**Comment by Arviksain** [comment]
Hi @PaulAndersonS Can u please check this issue at a priority.

Due to all tabitems bindincontext initialized when 1st tabview loaded, that is taking long time for doing the operations for huge load pages. So that should not be the scenaio.

you need to set like when tabview loaded, whatever tabitem we are clicking only that tabitem's content bindingcontext should be initialized not all

**Comment by Arviksain** [comment]
Hi @naveenkumar-sanjeevirayan , Can u please solve this issue. because data loading & binding is high with nested tabs. So, don't want to load every tabs in a single shot, one by one tapped & loaded

**Comment by PaulAndersonS** [comment]
Hi @Arviksain,

We are checking on this with high priority. We will update you further with the details
