### ISSUE TITLE
Bug Report: Syncfusion.Maui.Toolkit.SfView.Add is inaccessible in Release mode

### ISSUE THREAD

**Issue by agustinbishel** [syncfusion/maui-toolkit#37]
Hello everyone!

I'm encountering an issue with Syncfusion.Maui.Toolkit in my .NET MAUI application that only happens in Release mode. Below, I’m providing the details of the problem to help investigate and find a solution. I’d appreciate any guidance or insights you can offer!

When building my .NET MAUI application in Release mode, I encounter the following error during compilation:

> Method Syncfusion.Maui.Toolkit.SfView.Add(Microsoft.Maui.Controls.View) is inaccessible from method 

This issue does not occur when building in Debug mode, where everything works as expected. It seems to be related to how accessibility is handled for the SfView.Add method, potentially due to compiler optimizations or restrictions in Release mode.

Steps to Reproduce

Use Syncfusion.Maui.Toolkit in a .NET MAUI project.

Add a chips:SfChip in XAML, like so:

```
<chips:SfChip Text="Some Text"
              FontSize="14"
              Clicked="Chip_OnClicked" />
```
              
Build the application in Release mode.

Observe the runtime error when the page is displayed.

Expected Behavior

The application should compile and run in both Debug and Release modes without accessibility issues.

Actual Behavior

The build fails in Release mode with the error mentioned above.

Environment

.NET MAUI version: 8.0.100
Syncfusion.Maui.Toolkit version: 1.0.2
Target frameworks: iOS
Build mode: Release

**Comment by Choza-rajan** [comment]
@agustinbishel, The reported issue was not reproducible with MAUI version 8.0.43 or the latest version 9.0.1. Please recheck using these versions and share any relevant details with us.

**Comment by PaulAndersonS** [comment]
@agustinbishel We have added the "s/needs-repro" label to this issue, indicating that we require steps and sample code to reproduce the issue before taking further action. Please try to create a minimal sample project/solution or code samples that reproduce the issue.

This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you return to this issue after that time.
